name: PR Commenter
description: A Buildkite plugin which will comment on pull requests
author: "@mcncl"
requirements:
  - go
  - bash
configuration:
  properties:
    message:
      type: string
    secret-name:
      type: string
    allow-repeats:
      type: boolean
      description: "Allow identical comments to be posted every time the plugin is run"
      default: true
    message-id:
      type: string
      description: "Unique ID of the message to be posted, used to identify existing comments (allow-repeats: false). Use if plugin is used more than once in same job."
  required:
    - secret-name
